x=("apple","banana","mango")
print(x)
y=list(x)
y[1]="kiwi"
x=tuple(y)
print(x)
print("add item using append")
z=list(x)
z.append("orange")
x=tuple(z)
print(x)
print("add tuple to tuple")
a=("red","green")
b=("blue",)
a+=b
print(a)
print("remove item by concerting into the list")
c=list(a)
c.remove("red")
a=tuple(c)
print(a)