import datetime
x=datetime.datetime.now()
print(x)
print(x.hour)
print(x.year)
print(x.day)
print("Weekday, short version ->",x.strftime("%a"))
print("Weekday full ->",x.strftime("%A"))
print("weekday as number",x.strftime("%w"))
print("Day of month 01-31->",x.strftime("%d"))
print("Month name, short version->",x.strftime("%b"))
print("Month name, full version->",x.strftime("%B"))
print("	Month as a number 01-12->",x.strftime("%m"))
print("	Year, short version, without century->",x.strftime("%y"))
print("	Year, full version, without century->",x.strftime("%Y"))
print("	Hour 00-23->",x.strftime("%H"))
print("Hour 00-12->",x.strftime("%I"))
print("	AM/PM->",x.strftime("%p"))
print("Minute 00-59->",x.strftime("%M"))
print("	Second 00-59->",x.strftime("%S"))
print("Microsecond 000000-999999->",x.strftime("%f"))
print("	Century",x.strftime("%C"))
print("Local version of date->",x.strftime("%x"))
print("	Local version of time->",x.strftime("%X"))
print("	Day number of year 001-366->",x.strftime("%j"))
print("Week number of year, Sunday as the first day of week, 00-53->",x.strftime("%U"))
print("	Week number of year, Monday as the first day of week, 00-53->",x.strftime("%W"))

